data:
  image_root: data/raw/csiro-biomass
  image_size: 1024
  black_padding_probability: 0.2
  train_manifest: data/processed/csiro-biomass/metadata/train_wide.parquet
  fold_manifest: data/processed/csiro-biomass/folds/folds_v1.parquet
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  interpolation: bicubic

model:
  backbone_name: dinov3_vitl16
  backbone_source: torchhub
  backbone_repo: facebookresearch/dinov3
  pretrained: true
  backbone_weights: artifacts/pretrained/modelscope/facebook/dinov3-vitl16-pretrain-lvd1689m/dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth
  backbone_check_hash: false
  fusion_dim: 1024
  trunk_dim: 1024
  num_attention_heads: 8
  dropout: 0.1

train:
  experiment_name: dinov3-vitl-1024
  output_dir: artifacts/server/dinov3-vitl-1024
  folds: [0, 1, 2]
  seeds: [42, 3407]
  batch_size: 2
  grad_accum_steps: 8
  num_workers: 8
  amp: true
  cls_weight: 0.3
  stages:
    - freeze_backbone: true
      optimizer: {name: adamw, lr: 2.0e-4, weight_decay: 1.0e-4}
      scheduler: {name: cosine, epochs: 5, warmup_steps: 20}
    - freeze_backbone: false
      unfreeze_last_n_blocks: 0
      optimizer: {name: adamw, lr: 3.0e-5, weight_decay: 1.0e-4}
      scheduler: {name: cosine, epochs: 12, warmup_steps: 30}
